:: Made by Xenoxix - IK DC
:: Please don't remove this message

@echo off
if /i "%~1" EQU "tAff" setlocal ENABLEDELAYEDEXPANSION&title;Snake&goto AFF
if defined $ (
   setlocal ENABLEDELAYEDEXPANSION
   title;Snake
   mode con cols=60 lines=20
   call :Reset
   call :NewEat
   call :DrawScore
   echo;-h 0
   goto Menu) else (
   set $=.
   if not exist batbox.exe call :makebatbox
   if not exist darkbox.exe call :makedarkbox
   if not exist darkbox_i.exe call :makedarkbox_i
   (start /b "" call "%~0" "tAff"
   call "%~0")|darkbox
)

:Aff
for %%A in (1 2 3 4 5 6 7 8 9 A B C D E F) do (
   echo;-gcdrd 18 0 0x0%%A "| Snake | Made by " "IK DC"
   batbox /w 500
)
goto Aff


:DrawTable
echo;-r -19gd
for /l %%A in (0,1,18) do echo;0 %%A "                                                            "
goto :EOF


:DrawScore
echo;-g 0 0 -2cd 0x07 "Score : " 0x0e "%Score%" -r
goto :EOF

:NewEat
set /a EatX=%random%%%59,EatY=%random%%%18+1
for %%A in (%Stack%) do (
      for /F "tokens=1,2 delims=-" %%B in ("%%A") do (
         if "%EatX%" EQU "%%B" if "%EatY%" EQU "%%C" goto NewEat
      ))
echo;-gca %EatX% %EatY% 0x0b 6
goto :EOF

:DrawSnake
set "Stack=%Stack% %PosX%-%PosY%"
echo;-gcd %PosX% %PosY% 0xa0 " "
for %%A in (%Stack%) do (
      for /F "tokens=1,2 delims=-" %%B in ("%%A") do (
         echo;-gd %%B %%C " "
      ))
for /f "tokens=1,* delims= " %%A in ("%Stack%") do (
      set Stack=%%B
      echo;-r
      for /f "tokens=1,2 delims=-" %%C in ("%%A") do echo;-gd %%C %%D " "
   )
goto :EOF

:Reset
set /a OLDY=PosY=Score=1,OLDX=PosX=LastPressed=1,Speed=90
set Stack=0-2
goto :EOF

:menu
darkbox_i /k_&if !Errorlevel! NEQ 0 (
if !Errorlevel! EQU 77 (if %LastPressed% NEQ 2 (set /a LastPressed=1&if %PosX% LSS 59 (set /a PosX+=1) else set /a PosX=0) else call :LastPressed
   ) else if !Errorlevel! EQU 75 (if %LastPressed% NEQ 1 (set /a LastPressed=2&if %PosX% GTR 0 (set /a PosX-=1) else set /a PosX=59) else call :LastPressed
   ) else if !Errorlevel! EQU 72 (if %LastPressed% NEQ 4 (set /a LastPressed=3&if %PosY% GTR 1 (set /a PosY-=1) else set /a PosY=18) else call :LastPressed
   ) else if !Errorlevel! EQU 80 (if %LastPressed% NEQ 3 (set /a LastPressed=4&if %PosY% LSS 18 (set /a PosY+=1) else set /a PosY=1) else call :LastPressed
   ) else if !Errorlevel! EQU 27 (call :Pause&call :LastPressed) else call :LastPressed) else call :LastPressed
for %%A in (%Stack%) do for /F "tokens=1,2 delims=-" %%B in ("%%A") do (
         if "%PosY%" EQU "%%C" if "%PosX%" EQU "%%B" (
            echo;-gcd 45 0 0x0c "Game Over"
            call :Death&goto Menu
      ))
if %PosX% EQU %EatX% if %PosY% EQU %EatY% (
   set /a Score+=1
   if %Speed% GTR 20 set /a Speed-=2
   set "Stack=%Stack% %PosX%-%PosY%"
   call :DrawScore
   call :NewEat
)
call :DrawSnake
batbox /w %Speed%
goto menu

:LastPressed
if %LastPressed% EQU 1 (if %PosX% LSS 59 (set /a PosX+=1) else set /a PosX=0) else if %LastPressed% EQU 2 (if %PosX% GTR 0 (set /a PosX-=1) else set /a PosX=59
   ) else if %LastPressed% EQU 3 (if %PosY% GTR 1 (set /a PosY-=1) else set /a PosY=18) else if %LastPressed% EQU 4 (if %PosY% LSS 18 (set /a PosY+=1) else set /a PosY=1)
goto :EOF


:Pause
echo;-gcd 45 0 0x0a "Pause"
darkbox_i /k
if !Errorlevel! NEQ 27 goto Pause
echo;-rgd 45 0 "      "
goto :EOF

:Death
darkbox_i /k
if !Errorlevel! NEQ 13 goto Death
call :Reset
call :DrawTable
call :DrawScore
call :NewEat
goto :EOF

:makedarkbox_i
del out.file 2>NUL
(
echo;TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAAAAAAAAAAAAAAAAAOAADwMLAQYAABAAAAAQAAAAMAAAcEQAAABAAAAAUAAAAABAAAAQAAAAAgAABAAAAAAAAAAEAAAAAAAAAABgAAAAEAAAAAAAAAMAAAAAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAABQAADYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFVQWDAAAAAAADAAAAAQAAAAAAAAAAIAAAAAAAAAAAAAAAAAAIAAAOBVUFgxAAAAAAAQAAAAQAAAAAYAAAACAAAAAAAAAAAAAAAAAABAAADgVVBYMgAAAAAAEAAAAFAAAAACAAAACAAAAAAAAAAAAAAAAAAAQAAAwDMuOTEAVVBYIQ0JAgiGNv0X5uFIxiIiAABOBAAAAAwAACYAAKZvl1/+VYnlgew0AJBTuPb/UOgKBISJbmNt90X8uBEUUIsIEYwIFLlk2/vvEACJCI1F+FC4ARwJ5CCd7f72lA+3DYP4Ag+F3EW4BB/otd8+1gPgH5yDxAwrDA+/TeBCsm1PswgQ4uxq3AX0O/fty9jcg+ABQgAPhDM9cItNdU339tiD4QIa1IP5FAXpA7nb/fuLfAm+uAMoTdSJAQ4BjkEn5AAZAtD7uCDda5MCSKhB0EW6M3IED/QFd9ghgx3YO1/cWQ9kewQYD5fBZ8wBY5KMPMi4B2i4Bsyb7P0QTQ++RQhRNJxWI7xw7AhHkv5JW8nDohCwwmMnAUYIOchnMNr29mYCDIPABDOJTfAK8FDLWWTrPC2hGQ4vCnTdQzA4AsoYQBlRhdi3PJmkBBR8TK9+loXD9FDh5fwA6Nn9MiHf1oYjEB6rAdjmAjK6V4oCc8ju/9hfPQ+VwMHgGMH4GFBqAul5+c83ygSckoP4aHSGa3TEb/Z+eW10gXl0m+vgO6k2R5russ0Oi56LiyBAEGKuM8KsfyMtmDvs5AAKILR4GzMPIXIEd4UTIv17CO+8DVQDQxLEiEX/yDdZmL2h4Bs63uzrvgk+Rf8ITaEJ+U6Rw2YsAoBJ0J1vgi8NzCwAjthy9mIBE9QIRe9qnr5tNdThBTwiQEPY3HSN8kVrJtweE4vpZnrSiwGfWzXgi2r+v80G5OwJhywkVY1sJARRiemB7V/H75sT6YUBLQBIPQR97CnBD87tjaWJjcw5/2AEPOzDsbFZ2wgAAQlMCJxdd9mb7MOLZegR9Kn/ABZWe+e2FKQrA18E/FWLbR/b7O3uRCSNADHABARkodHZSO0beXMjBwy4PBAdFNO6hrfvCGSjIF2s/yXMrAAH0BlkkEHU3OBkkEEG5OjskEEGGfD0+IOcHGT8ACEECCrCzCAMAP8f+4olZCACCgBkYXJrYm94X2kgF+z//y0gSW5wdXQgbW9kdWxlIGZvciAcGi+7/X9UU25ha2U0MQpVc2FnHDogN1st//2v+2tbX11dB20EeV0KTm90IictJyBj3m7/9mFuIGIMcmVwbGFjZXJieRYvJwqtqCKkeTYXAIENYMwQX5b/XwFHZXRTdGRIYW5kbGVTQ29ucyDYu7dvC01vZA9SZWFkEP2n2b4bQTlt3G1lbW1vdnN/+9YkdB1vd2VyCHByaW50ZgcoNt/9bXMFX2tiaGl0B2dldGNoX3PbbfffCF9hcHBfdHlwNl9jWHRyO2a2e9u9cBskbWE+YXJnOmV4OHaz7z9YY3B0RmlsdFtfEwZjZfIEjt0VX2iwcjNaUEWE/BPyTAEC4AAPAwsBBjd7mu5UEw0QIEALNifbsEkEBxcwXDew73XvAw8oEAcGhCwvgdiQIDwwkHQDzFdILsILtrsaeHQHCAWQ7gb33v8W6mAuZGF0YfEb+7/lwr7oCCdAwBtcIQAAwC3OB5AAAAD/AAAAAAAAAAAAAAAAAGC+FUBAAI2+68///1eDzf/rEJCQkJCQkIoGRogHRwHbdQeLHoPu/BHbcu24AQAAAAHbdQeLHoPu/BHbEcAB23PvdQmLHoPu/BHbc+QxyYPoA3INweAIigZGg/D/dHSJxQHbdQeLHoPu/BHbEckB23UHix6D7vwR2xHJdSBBAdt1B4seg+78EdsRyQHbc+91CYseg+78Edtz5IPBAoH9APP//4PRAY0UL4P9/HYPigJCiAdHSXX36WP///+QiwKDwgSJB4PHBIPpBHfxAc/pTP///16J97k1AAAAigdHLOg8AXf3gD8AdfKLB4pfBGbB6AjBwBCGxCn4gOvoAfCJB4PHBYjY4tmNvgAgAACLBwnAdDyLXwSNhDAAQAAAAfNQg8cI/5Y8QAAAlYoHRwjAdNyJ+VdI8q5V/5ZAQAAACcB0B4kDg8ME6+H/llBAAACLrkRAAACNvgDw//+7ABAAAFBUagRTV//VjYefAQAAgCB/gGAof1hQVFBTV//VWGGNRCSAagA5xHX6g+yA6VTN//8AAAAAAAAAAAAAAABgUAAAPFAAAAAAAAAAAAAAAAAAAG1QAABYUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4UAAAhlAAAJZQAACmUAAAtFAAAMJQAAAAAAAA0FAAAAAAAABLRVJORUwzMi5ETEwAbXN2Y3J0LmRsbAAAAExvYWRMaWJyYXJ5QQAAR2V0UHJvY0FkZHJlc3MAAFZpcnR1YWxQcm90ZWN0AABWaXJ0dWFsQWxsb2MAAFZpcnR1YWxGcmVlAAAARXhpdFByb2Nlc3MAAABwdXRzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
)>>out.file
(certutil -f -decode "out.file" "darkbox_i.exe")>NUL
Del out.file>NUL
goto :EOF



:makedarkbox
del out.file 2>NUL
(
echo;TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAAAAAAAAAAAAAAAAAOAADwMLAQYAABAAAAAQAAAAMAAA0EcAAABAAAAAUAAAAABAAAAQAAAAAgAABAAAAAAAAAAEAAAAAAAAAABgAAAAEAAAAAAAAAMAAAAAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAABQAADYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFVQWDAAAAAAADAAAAAQAAAAAAAAAAIAAAAAAAAAAAAAAAAAAIAAAOBVUFgxAAAAAAAQAAAAQAAAAAoAAAACAAAAAAAAAAAAAAAAAABAAADgVVBYMgAAAAAAEAAAAFAAAAACAAAADAAAAAAAAAAAAAAAAAAAQAAAwDMuOTEAVVBYIQ0JAgiTOmOSMkTdVwIjAACyBwAAABYAACYAALrfLt/8VYnlgewAkFO49f9Q6AoLxIkFPhbb/QQkQAC4CARQiwsXzFvJw+b+R8YwBItFCIP4AA+MEQ0L/XXNyAwF6QNaBJEPv/us6b4iZolF/AcM/jmJ4LkGDNjH/lGNTfxRV9SDxAxm3O62soWGTgUMDPL9/f2LTQgByLm8OcG4Bg+fwISExb6BHesoEPAmJ0f+uT4NDlUMAdG6yrnBI83LdquD+UEBLQ4Mfs2dIwEyjSe5AC2wRw5bCK0IjUX4q8LfAzvkkAFwBJIPvjgYMjcssnM07HZ4k0MADChGCN1LIBz+EhPaCoOE130Gr8n0VXGyy2JvIVC4IM1I9FrIPgC2Rg+3BRA2joTZWaxQBSoAYY0LRw+2B4Hgc4GEGQs7DAQkWEItv/edArME2zpVAm0EzM99uTxYIYPAIFAsawwM2LKV7QcDCnA1K5sNMDcUCyvSmQd5RyL+AQ+ONMAEZr5vG0UgKlGLCFGDHLn/ZrwHA3dlgQ6L6ID8sMjua/sTjhgEDGFkurOwPASkJGYm7LOUIIAAEySXvXf2QiciLOciDHbIlg5hAyAbNK2Mv5SVIev53pkxt/EYasTAMeAjLDnpmB8gCPizhHE2/AYw1JaZJ08f1IBQjQmOme1CM1xdO/ktWhS7OwmHDi9KBbETicFAPduVzIJ4CJ4iEVIP2Oawb/jKPJgbuApe9md+bjOTDEREArgBTvKdvQ0CP/iJAWdRQUxL1o0dZn8IX4mWFphsZadKLp91MYSlw5JAAKBh72QP4ZT9Bi3B66cx2QIZkKfBrlp2YLwJ8Pwph82SccvS9x9UL2BvGIwVUglnlq3riEX3kfceChkvGCf73VwUweAYwfgYUOvaoWCEZU0Umob8cMnZbyI5yA+DhQLgYeJ5yILBQZo/+FsCu5055PhkMwgtDAjZj5O+ZHESwwO40paxbBkg/+tb2JsdAjHjRFeEHMwVahgCbQa7QPeLDShEATJN9A8ssmG9RlHaui52wF7CFwFCRwGVUdkLdl6JBQpMGrPDZK9lCcQ7p2E2lpBsEnQPirhky8I68PDQCzYIDTyqhTj/fuwn0jtNbxgzEQswVrbBXgf6Iew6YhUU48IOCCNX7CHFHgjungtAB5qN7c98iwQjbg+PUgiNkP6EyDKybBFkKWRM+S5j22FHMAhiN/8RY57bYGZ2Q2cWgf5oGdkuWadySCBylpFtZM5vKKpxxtlGtktzFol3CMffx8iGbPj4emcEVoxBWFi3KfjcWXrhGP/x67t8CClzB4XiphVAhO2xewlYYYH4i5kkIbJfZGP4JiA0iAGBZiR7WGHrshKlG0gcLKuICBkakMOSNZe0EOnJFqFOIpTAzjZgzyW9+zz30v5cWwcK/+doCQe45SFdz2E/SjPwd9I7bDBv9OU4a4GBtbF3XIRlLJWM8BYlEAHKFgK1kPvZmyKJykGJKJjRMgbOnYQB+gdqLEN6fg3ozQuFAStWiyy8hA1AAxX9hu2EM4wr1DXUVGNNt50wCtgD3OQmlPCk6S4UixOLiwMsWJK2zXQ14A7giYjR3f/Sh7VVjWwkBFGJ6YH7GyWFQfvXsAsAlT0EfewpwQ/293S77InMv/9gOcOoQIsAATdjY7MJuEScnMOLZW277rLoEaSp/wBSG6RntPv2zgNfDKxVi20IjUQkjQAxm9tmdxMEZKHR2YQjBwx9b9/IuHgQHRTTCGSjIF2Qz8DPrE8lLBIHMEEGGWRUNDgGGWSQPEBESBlkkEFcYGRkkEEGaGxwkEEGGXR4fEEGGWSAhIgGGWSQjEyQlBlkkEGYnKCRmUEGpKgA/f9fAS8/AGRhcmtib3ggLSBGYXN0f/f/C1NvcnRhYmxlIENvbnNvB0lPIFNlcnb/t61rAiFBIGkRVGVkZHkgKFRTbv3/7f9ha2U0MSkKVXNhZxY6IGNhbGwgZ2FtZV9maWsHu705LmJhTnwgXwpNWCPmtm17aW5mBm0XaVwgHTJv/3f/aHR0cDovLypjaC54b28uaXQvcFM0OTe7bQW2LhptxDxzM2cgfWtvb21yNy1JbnZiaWQgAzbbI9taEgpzIE5vhG+/td+2bWBuI3NwZWNph6sAIgAgCmwFRNYNCTQDbAaCKmAsEWKX4L8BR2V0U3RkSDhsZQ2C/z8J/lNjcmVlbkJ1ZmZlckm/PclWvBtTQ3VyBnJQb3NpbGHPBM81GS8f7GcLFUZpbGwWT3V0cMCW4G8CQ2hhcmFj1UEcfWDbH0F0dHJpYgdlTlRleNNst4QYEWVw0W1UumXr/m1lbW1vdhhfnGJmRnN720zXBmljCHM4Y21wJj3nboGzb2Mf5x722sj/JGlzZGlnaXR0aRAlgu3O2nA2NWg9Z2VGu73m7h5vd2UIjDAoc3DF9v23X3RfcyJfYXBwX3R5cA9jtJt7rbU7LIYbPndpzrnvtm5AZ21fWGNwdPL7DAi35mZHBkUVX2iQQP4R4HIzf1BFAABMAQLTPZD/4AAPAwsBBpAaDRA26WZPIEALNgQHzvZkGxcwZ1cPAy57A/soEAcGAPC9CgToTzz9LCGd4UCyH4QudOoHuG5hb7AMkA63I5rIvtP9YC5kYXRh4DT7BsCY7XdCDcAbNCJ3rgAAAAAAABIA/wAAAAAAAAAAAGC+FUBAAI2+68///1eDzf/rEJCQkJCQkIoGRogHRwHbdQeLHoPu/BHbcu24AQAAAAHbdQeLHoPu/BHbEcAB23PvdQmLHoPu/BHbc+QxyYPoA3INweAIigZGg/D/dHSJxQHbdQeLHoPu/BHbEckB23UHix6D7vwR2xHJdSBBAdt1B4seg+78EdsRyQHbc+91CYseg+78Edtz5IPBAoH9APP//4PRAY0UL4P9/HYPigJCiAdHSXX36WP///+QiwKDwgSJB4PHBIPpBHfxAc/pTP///16J97mUAAAAigdHLOg8AXf3gD8AdfKLB4pfBGbB6AjBwBCGxCn4gOvoAfCJB4PHBYjY4tmNvgAgAACLBwnAdDyLXwSNhDAAQAAAAfNQg8cI/5Y8QAAAlYoHRwjAdNyJ+VdI8q5V/5ZAQAAACcB0B4kDg8ME6+H/llBAAACLrkRAAACNvgDw//+7ABAAAFBUagRTV//VjYefAQAAgCB/gGAof1hQVFBTV//VWGGNRCSAagA5xHX6g+yA6TDR//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYFAAADxQAAAAAAAAAAAAAAAAAABtUAAAWFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeFAAAIZQAACWUAAAplAAALRQAADCUAAAAAAAANBQAAAAAAAAS0VSTkVMMzIuRExMAG1zdmNydC5kbGwAAABMb2FkTGlicmFyeUEAAEdldFByb2NBZGRyZXNzAABWaXJ0dWFsUHJvdGVjdAAAVmlydHVhbEFsbG9jAABWaXJ0dWFsRnJlZQAAAEV4aXRQcm9jZXNzAAAAX2lvYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
)>>out.file
(certutil -f -decode "out.file" "darkbox.exe")>NUL
Del out.file>NUL
goto :EOF

:makebatbox
del out.file 2>NUL
(
echo;TVqAAAEAAAAEABAA//8AAEABAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQokAAAAAAAAAABQRQAATAEBAGOZxlMAAAAAAAAAAOAADwELAQFGAAYAAAAGAAAAAAAAABAAAAAQAAAAEAAAAABAAAAQAAAAAgAAAQAAAAAAAAAEAAAAAAAAAAAgAAAAAgAA9ugAAAMAAAAAEAAAABAAAAAAAQAAAAAAAAAAABAAAAAAAAAAAAAAAFUTAABzAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC5mbGF0AAAA/AUAAAAQAAAABgAAAAIAAAAAAAAAAAAAAAAAAGAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo2BVAAGoAaNgVQABozBVAAGjIFUAA/xV0FUAAavX/FVQUQACj1BVAAGr2/xVUFEAAo9AVQADomgIAAEOKE4DKIDH/ZrkLADqXSBNAAA+EeQIAAEdn4vDp2v///+hXAgAAUP811BVAAP8VXBRAAOnD////gHsBXw+FDgAAAP8VfBVAAIXAD4Sr/////xVwFUAAPeAAAAAPhQsAAAD/FXAVQAAF/wAAAFD/FXgVQADoBQIAAAMFBxNAACX//wAAo9wVQADo8AEAAAMFCxNAAMHgEAEF3BVAAP813BVAAP811BVAAP8VYBRAAOlI////6MUBAADHBQ8TQAAAAAAAow8TQABoDxNAAGj1EkAA/xVsFUAA6R/////ouQEAAFNo9RJAAP8VbBVAAOkJ////ahj/NdAVQAD/FVgUQABo2BVAAGoBaOAVQAD/NdAVQAD/FWQUQACDPdgVQAAAD4TN////ZoM94BVAAAIPhb/////3BfAVQAD9////D4Wv////iz3kFUAAif7B7xCB5v//AACh6BVAAIXAD4SR////AwXwFUAAUFdWaPgSQAD/FWwVQADpgf7//2oY/zXQFUAA/xVYFEAAaNgVQABqAWjgFUAA/zXQFUAA/xVkFEAAiz3kFUAAif7B7xCB5v//AACh6BVAAFBXVmj4EkAA/xVsFUAA6TL+///orwAAAFD/FWgUQADpIf7//+ieAAAAowcTQADolAAAAKMLE0AA6Qj+//9o9BVAAP811BVAAP8VcBRAAOh0AAAAo/gVQABo9BVAAP811BVAAP8VbBRAAOnX/f//6FQAAACJx/8VdBRAAFdQ/xUQFEAA6b39///oOgAAAEBo2BVAAFD/NdQVQAD/FXgUQADpoP3//+g6AAAAgDsAdQW7AAAAAGgCAAIAagBT/xXwE0AA6X79///oGAAAAGoAagBT/xWAFUAAg8QMw8HnAv+nFBNAAIMFzBVAAASLHcwVQACLG4XbD4QBAAAAw2oA/xV4FUAAJXMAJWQ6JWQ6JWQAJWQ6JWQAAAAAAAAAAAAAAAAAAHMQQACuEEAA7hBAAFwQQAAXEUAALRFAALURQAAVEkAABBJAAC4SQACWEkAAXxJAAHkSQABrZ2FjZG15b3doc3BmUBUAAAAAAAAAAAAAuRMAAGwVAAAoFAAAAAAAAAAAAADEEwAAVBQAAAgUAAAAAAAAAAAAANITAAAQFAAA6BMAAAAAAAAAAAAA3hMAAPATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE1TVkNSVC5ETEwAS0VSTkVMMzIuRExMAABVU0VSMzIuRExMAABXSU5NTS5ETEwA+BMAAAAAAAD4EwAAAAAAAAAAUGxheVNvdW5kQQAAAAAYFAAAAAAAABgUAAAAAAAAAABTaG93V2luZG93AAAAAIAUAACQFAAAohQAALwUAADYFAAA7BQAAPQUAAAMFQAAJBUAADgVAAAAAAAAgBQAAJAUAACiFAAAvBQAANgUAADsFAAA9BQAAAwVAAAkFQAAOBUAAAAAAAAAAEdldFN0ZEhhbmRsZQAAAABTZXRDb25zb2xlTW9kZQAAAABTZXRDb25zb2xlVGV4dEF0dHJpYnV0ZQAAAFNldENvbnNvbGVDdXJzb3JQb3NpdGlvbgAAAABSZWFkQ29uc29sZUlucHV0QQAAAFNsZWVwAAAAU2V0Q29uc29sZUN1cnNvckluZm8AAAAAR2V0Q29uc29sZUN1cnNvckluZm8AAAAAR2V0Q29uc29sZVdpbmRvdwAAAABTZXRDb25zb2xlRGlzcGxheU1vZGUAiBUAAJIVAACcFQAArBUAALQVAAC+FQAAAAAAAIgVAACSFQAAnBUAAKwVAAC0FQAAvhUAAAAAAAAAAHByaW50ZgAAAABfZ2V0Y2gAAAAAX19nZXRtYWluYXJncwAAAGV4aXQAAAAAX2tiaGl0AAAAAHN0cnRvbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
)>>out.file
(certutil -f -decode "out.file" "batbox.exe")>NUL
Del out.file>NUL
goto :EOF


